version: '3.8'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


  fastapi:
    build: .
    ports:
      - "8008:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${CONTAINER_DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge